# Generated by Django 2.2.12 on 2020-10-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teaches',
            field=models.BooleanField(default=False),
        ),
    ]
