# Generated by Django 2.2.12 on 2020-10-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiuser', '0002_auto_20201007_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='user', to='auth.Group'),
        ),
    ]
